export const GET_MOVIE_REQ = "GET_MOVIE_REQ";
export const GET_MOVIE_SUCCESS = "GET_MOVIE_SUCCESS";
export const GET_MOVIE_FAILURE = "GET_MOVIE_FAILURE";
export const FILTER_DATA = "FILTER_DATA";

export const GET_CLICKED_MOVIE_REQ = "GET_CLICKED_MOVIE_REQ";
export const GET_CLICKED_MOVIE_SUCCESS = "GET_CLICKED_MOVIE_SUCCESS";
export const GET_CLICKED_MOVIE_FAILURE = "GET_CLICKED_MOVIE_FAILURE";
